### ISSUE TITLE
Potion usage line is too long

### ISSUE THREAD

**Issue by NoamGeller** [Nog-Frog/pokered#137]
![Screenshot_20200807-184153](https://user-images.githubusercontent.com/12798171/89663104-b7b9ca80-d8dd-11ea-997b-58ab71362d61.png)
Found the relevant line, number 1446 at data/text/text_2.asm, but changing it from text to line somehow made it fetch the antidote text below it, and changing to נ"פ also added some weird character, invisible in my editor

Also, the colors for כידרור are buggy

**Comment by NoamGeller** [comment]
Oak's aide in data/text/text_1.asm also has long lines after text_decimal

**Comment by Nog-Frog** [comment]
היי, אני רואה שבהודעה כתוב שהוא שיחזר 18 נ"פ. האם זה המספר הנכון, או שיש כאן בעיה גם במספר?
