### ISSUE TITLE
Debugging the game

### ISSUE THREAD

**Issue by NoamGeller** [Nog-Frog/pokered#50]
I want to check how my changes appear in the game, but I don't want to play all of it to get to a certain point.
Is there a way to make the game start at a location other than Pallet?

I tried to compile the game and load it with a completed `.sav` file I had, but the game considers it corrupted:
![pokered](https://user-images.githubusercontent.com/12798171/84588875-8d92e180-ae33-11ea-9ffd-b87f869c5d4c.png)
My save file did load correctly with a rom compiled from the original pokered repo, so it's something here that made the save file unreadable.
Do you know if there is a specific change to the save file, or did its whole structure changed? If I did start playing the game, should I assume each commit will make the save file invalid?

Keep up the good work 😄

**Comment by Nog-Frog** [comment]
היי!
אני יודעת שאכן יש שינויים בצורה שבה המשחק קורא סייבים.
לצערי, לא חקרתי את העניין לעומק, אז אני לא בטוחה למה. אבל אני יודעת שזה לא בדיוק באג אלא פשוט שוני.
מצאתי שאם אני פותחת את הסייב בגרסה המקומפלת של pret/pokered, הולכת למקום שאפשר לעוף ממנו, שומרת, פותחת בפוקירד המתורגם, ואז עפה לאנשהו ואז שומרת - הסייב מתפקד בסדר.
עם זאת, התבצעו שינויים לאחרונה שייתכן שחסמו גם את האפשרות הזאת. מצרפת את הסייב שלי כדי שתוכל לבדוק את השינויים שלך.
***שים לב!!! הסייב הזה קצת דפוק, בטעות ביצעתי איזה גליץ' שידוע בזה שהוא מקלקל חלק מהסייב דאטה. במיוחד חלק מה-PC boxes מכילות פוקימונים לא ולידים, ואם תסתכל עליהם יכול להיות שעוד מהסייב יהרס. אז זהירות מה-PC boxes האחרות.***
(אל תנסה לעשות לו unzip. גיט הרשה לי להעלות רק אם זה האקסטנשן .zip. פשוט תשנה את השם שלו ל-pokered.sav וזה יעבוד.)
[pokered.zip](https://github.com/Nog-Frog/pokered/files/4776141/pokered.zip)

**Comment by Nog-Frog** [comment]
תעדכן אם עבר ואם מצאת עוד מידע בנושא. אנסה לברר בינתיים לגבי מה אפשר לעשות כך שסייבים יהיו קומפטבילים בין הגרסאות.

**Comment by NoamGeller** [comment]
תודה, הסייב שלך עובד טוב.
לא הצלחתי לגרום לסייב שהיה לי לעבוד בגרסה העברית, גם אחרי ששמרתי עליו עם הגרסה של pret/pokered.

**Comment by Nog-Frog** [comment]
היי! רציתי לעדכן שבקומיט האחרון השתנו כמה דברים, ועכשיו סייבים שעובדים על pret/pokered עובדים גם על Nog-Frog/pokered. זה כולל גם סייבים מהמשחק המקורי. :)
רק שים לב שאתה מעדכן את הפורק שלך עם הקומיטים האחרונים מהפורק שלי.
